name: Build and Deploy Nuget Package

on:
  push:
    branches:
      - main

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.4.21255.9'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack project
        run: dotnet pack --configuration Release

      - name: Deploy Nuget package
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ env.NUGET_API_KEY }}
          nuget-version: ${{ github.sha }}
        run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json
